"""add field

Revision ID: 0051e5915a95
Revises: c9e31f652513
Create Date: 2025-11-07 18:09:33.342812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0051e5915a95'
down_revision: Union[str, None] = 'c9e31f652513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('is_active', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizes', 'is_active')
    # ### end Alembic commands ###
