"""add new settings

Revision ID: 1708b0d7080b
Revises: a8094e729b69
Create Date: 2025-11-10 13:37:54.686027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from core.db.models import SettingModel
from sqlalchemy.orm import Session
# revision identifiers, used by Alembic.
revision: str = '1708b0d7080b'
down_revision: Union[str, None] = 'a8094e729b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    session = Session(bind)
    session.add(SettingModel(key="AdminSetting", value='{"admin_ids": [6730840793, 5003710675]}'))
    session.add(SettingModel(key="MODE", value='{"lang": "RU"}'))
    session.commit()
    session.close()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind)
    session.execute(sa.text("delete from settings where true"))
    session.commit()
    session.close()
    # ### end Alembic commands ###
