"""add user status

Revision ID: 6fef9f632f4c
Revises: 05242272e354
Create Date: 2026-02-11 17:31:07.860035

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fef9f632f4c"
down_revision: Union[str, None] = "05242272e354"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("last_sent", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("user_status_pkey")),
    )
    op.create_index(op.f("user_status_user_id_idx"), "user_status", ["user_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("user_status_user_id_idx"), table_name="user_status")
    op.drop_table("user_status")
    # ### end Alembic commands ###
