"""add tracking

Revision ID: bb767764ee82
Revises: 1708b0d7080b
Create Date: 2026-02-11 13:41:36.149640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb767764ee82'
down_revision: Union[str, None] = '1708b0d7080b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('user_id', sa.String(50), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tracking_pkey'))
    )
    op.create_index(op.f('tracking_timestamp_idx'), 'tracking', ['timestamp'], unique=False)
    op.create_index(op.f('tracking_user_id_idx'), 'tracking', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('tracking_user_id_idx'), table_name='tracking')
    op.drop_index(op.f('tracking_timestamp_idx'), table_name='tracking')
    op.drop_table('tracking')
    # ### end Alembic commands ###
