"""add quiz

Revision ID: c9e31f652513
Revises: ea4330c33c98
Create Date: 2025-11-07 13:05:07.508548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e31f652513'
down_revision: Union[str, None] = 'ea4330c33c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('current_question', sa.SmallInteger(), nullable=False),
    sa.Column('correct_answers', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('quizes_pkey'))
    )
    op.create_index(op.f('quizes_user_id_idx'), 'quizes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('quizes_user_id_idx'), table_name='quizes')
    op.drop_table('quizes')
    # ### end Alembic commands ###
