"""change tracking recorded_at

Revision ID: edf14145ddaf
Revises: bb767764ee82
Create Date: 2026-02-11 14:49:56.972583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edf14145ddaf'
down_revision: Union[str, None] = 'bb767764ee82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('tracking_timestamp_idx'), table_name='tracking')
    op.create_index(op.f('tracking_recorded_at_idx'), 'tracking', ['recorded_at'], unique=False)
    op.drop_column('tracking', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('tracking_recorded_at_idx'), table_name='tracking')
    op.create_index(op.f('tracking_timestamp_idx'), 'tracking', ['timestamp'], unique=False)
    op.drop_column('tracking', 'recorded_at')

    # ### end Alembic commands ###
